### PR TITLE
Integration of soft actor-critic algorithm (+ upgrade Flow to Python 3.7)

### PR DESCRIPTION
**Pull request by nathanlct**
## Pull request information

- **Status**: Ready to merge
- **Kind of changes**: New RL algorithm & upgrade to Python 3.7
- **Code affected**: Mostly environments, examples and tests

## Description

Integration of the [softlearning](https://github.com/rail-berkeley/softlearning) library in Flow, which implements [soft actor-critic](https://arxiv.org/abs/1801.01290) (SAC), as well as upgrade to Python 3.7.

Includes:
- two examples of ring and merge stabilization using SAC
- a visualizer `visualizer_sac.py` to simulate a policy trained using SAC
- a visualizer `ray_plot_progress.py` to plot any column(s) generated in the `~/ray_results/.../progress.csv` file
- unit tests
- upgrade of Flow to support Python 3.7 (implies upgrade to `tensorflow 1.13.1` and `numpy 1.16.0`)
- various bug fixes related to 3.7 upgrade (mainly: `redirect_output` has become obsolete in `ray.init`, and the checkpoint/save files produced by ray are slightly different)
- commented out pyglet renderer test (will be fixed later)

### CODE REVIEW

**Comment by nathanlct** [comment]
- [x] Visualizer is functional
- [x] The ring stabilization works
- [ ] Clean `exprunner.py` (remove what is not needed)
- [ ] Clean `stabilizing_the_ring.py` (maybe put all the params that will never/rarely change inside `exprunner.py`)
- [ ] Remove changes in `vehicle/aimsun.py` from this PR
- [ ] Finish wrapper for the methods that must be added in environment

**Comment by AboudyKreidieh** [comment]
@nathanlct can you fix these pep8 bugs:

```
./flow/visualize/visualizer_sac.py:38:56: E999 SyntaxError: invalid syntax
    checkpoint_dir = f"checkpoint_{args.checkpoint_num}"
                                                       ^
./flow/visualize/visualizer_sac.py:101:71: E502 the backslash is redundant between brackets
        help='The horizon for each rollout (by default the same as' + \
                                                                      ^
./flow/visualize/visualizer_sac.py:107:73: E502 the backslash is redundant between brackets
        help='Whether or not the policy should be made deterministic' + \
                                                                        ^
./flow/utils/softlearning.py:4:15: W291 trailing whitespace
"""
Utility functions for Flow compatibility with the softlearning library (SAC).
This includes: 
- ExperimentRunner class
- get_variant_spec function
- generate_experiment_kwargs function
- adapt_environment_for_sac function
"""
              ^
./flow/utils/softlearning.py:15:1: F401 'sys' imported but unused
import sys
^
./flow/utils/softlearning.py:24:1: F401 'softlearning.environments.utils.get_environment_from_params' imported but unused
from softlearning.environments.utils import get_environment_from_params
^
./flow/utils/softlearning.py:31:1: F401 'softlearning.misc.utils.deep_update' imported but unused
from softlearning.misc.utils import deep_update, datetimestamp
^
./flow/utils/softlearning.py:40:61: W291 trailing whitespace
            'flow_params': json.dumps(params['flow_params'], 
                                                            ^
./flow/utils/softlearning.py:41:61: W291 trailing whitespace
                                      cls=FlowParamsEncoder, 
                                                            ^
./flow/utils/softlearning.py:44:46: W291 trailing whitespace
        'flow_params': params['flow_params'],        
                                             ^
./flow/utils/softlearning.py:311:80: E501 line too long (80 > 79 characters)
        # TODO(hartikainen): target Qs should either be checkpointed or pickled.
                                                                               ^
./examples/sac/stabilizing_the_ring.py:8:1: F401 'json' imported but unused
import json
^
./examples/sac/stabilizing_the_ring.py:15:5: F401 'ray.rllib.agents.registry.get_agent_class' imported but unused
    from ray.rllib.agents.registry import get_agent_class
    ^
./examples/sac/stabilizing_the_ring.py:17:1: F401 'ray.tune.run_experiments' imported but unused
from ray.tune import run_experiments
^
./examples/sac/stabilizing_the_ring.py:18:1: F401 'ray.tune.registry.register_env' imported but unused
from ray.tune.registry import register_env
^
./examples/sac/stabilizing_the_ring.py:20:1: F401 'flow.utils.registry.make_create_env' imported but unused
from flow.utils.registry import make_create_env
^
./examples/sac/stabilizing_the_ring.py:26:80: E501 line too long (80 > 79 characters)
from flow.utils.softlearning import get_variant_spec, generate_experiment_kwargs
                                                                               ^
./examples/sac/stabilizing_the_ring.py:28:1: F401 'softlearning.misc.utils.deep_update' imported but unused
from softlearning.misc.utils import deep_update
^
./examples/sac/stabilizing_the_ring.py:103:16: E251 unexpected spaces around keyword / parameter equals
    flow_params = flow_params,
               ^
./examples/sac/stabilizing_the_ring.py:103:18: E251 unexpected spaces around keyword / parameter equals
    flow_params = flow_params,
                 ^
./examples/sac/stabilizing_the_ring.py:105:21: E251 unexpected spaces around keyword / parameter equals
    algorithm_params = {
                    ^
./examples/sac/stabilizing_the_ring.py:105:23: E251 unexpected spaces around keyword / parameter equals
    algorithm_params = {
                      ^
./examples/sac/stabilizing_the_ring.py:129:27: E251 unexpected spaces around keyword / parameter equals
    gaussian_policy_params = {
                          ^
./examples/sac/stabilizing_the_ring.py:129:29: E251 unexpected spaces around keyword / parameter equals
    gaussian_policy_params = {
                            ^
./examples/sac/stabilizing_the_ring.py:137:19: E251 unexpected spaces around keyword / parameter equals
    sampler_params = {
                  ^
./examples/sac/stabilizing_the_ring.py:137:21: E251 unexpected spaces around keyword / parameter equals
    sampler_params = {
                    ^
./examples/sac/stabilizing_the_ring.py:146:15: E251 unexpected spaces around keyword / parameter equals
    run_params = {
              ^
./examples/sac/stabilizing_the_ring.py:146:17: E251 unexpected spaces around keyword / parameter equals
    run_params = {
                ^
./examples/sac/stabilizing_the_ring.py:154:24: E251 unexpected spaces around keyword / parameter equals
    resources_per_trial = {
                       ^
./examples/sac/stabilizing_the_ring.py:154:26: E251 unexpected spaces around keyword / parameter equals
    resources_per_trial = {
                         ^
./examples/sac/stabilizing_the_ring.py:169:25: W291 trailing whitespace
        num_cpus=N_CPUS, 
                        ^
./examples/sac/stabilizing_the_ring.py:176:1: W293 blank line contains whitespace
        ^
./examples/sac/stabilizing_the_ring.py:176:1: W391 blank line at end of file
        ^
```

**Comment by nathanlct** [comment]
Upgraded to python 3.7.3, tensorflow 1.13.1 and numpy 1.15.0 (from 1.14.0) but travis raises errors when trying to build wheel for numpy (I also tried numpy 1.16.0). Travis is running python 3.5 though, I tried changing it to python 3.7 in travis.yml but then the build failed.

**Comment by nathanlct** [comment]
@AboudyKreidieh Do you have any idea how to fix this error? It's the pyglet renderer test I told you about that fails. Apparently it can't find a display so I would guess it has something to do with the config in `.travis.yml`?

```console
======================================================================
ERROR: test_pyglet_renderer (tests.fast_tests.test_pyglet_renderer.TestPygletRenderer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/flow-project/flow/tests/fast_tests/test_pyglet_renderer.py", line 75, in test_pyglet_renderer
    show_radius=show_radius)
  File "/home/travis/build/flow-project/flow/flow/renderer/pyglet_renderer.py", line 109, in __init__
    self.window = pyglet.window.Window(width=self.width,
  File "/home/travis/miniconda/envs/flow/lib/python3.7/site-packages/pyglet/__init__.py", line 384, in __getattr__
    __import__(import_name)
  File "/home/travis/miniconda/envs/flow/lib/python3.7/site-packages/pyglet/window/__init__.py", line 1896, in <module>
    gl._create_shadow_window()
  File "/home/travis/miniconda/envs/flow/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 208, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/travis/miniconda/envs/flow/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/travis/miniconda/envs/flow/lib/python3.7/site-packages/pyglet/window/__init__.py", line 501, in __init__
    display = get_platform().get_default_display()
  File "/home/travis/miniconda/envs/flow/lib/python3.7/site-packages/pyglet/window/__init__.py", line 1845, in get_default_display
    return pyglet.canvas.get_display()
  File "/home/travis/miniconda/envs/flow/lib/python3.7/site-packages/pyglet/canvas/__init__.py", line 82, in get_display
    return Display()
  File "/home/travis/miniconda/envs/flow/lib/python3.7/site-packages/pyglet/canvas/xlib.py", line 86, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
```

**Comment by AboudyKreidieh** [comment]
going to close since it is stale and SAC is implemented in stable-baselines; however, aspects of this PR may be useful later. We may come back to it

**Pull request closed without merging**
