### PR TITLE
Tests examples extended

### PR DESCRIPTION
**Pull request by AboudyKreidieh**
added tests to check if `use_inflows` and `use_traffic_lights` is working in the bay bridge example

### CODE REVIEW

**Comment by kjang96** [comment]
dibs

**Comment by kjang96** [comment]
LGTM

**Comment by eugenevinitsky** [comment]
@AboudyKreidieh Is there any reason this still has a DO NOT MERGE flag?

**Comment by AboudyKreidieh** [comment]
Hey sorry missed the message. Something's wrong with the starting positions on the bay bridge. Haven't had time to look at it yet, but it's a priority thing for me for sure. More soon hopefully.

**Comment by eugenevinitsky** [comment]
@AboudyKreidieh looks like this is passing now and the bay bridge tests are on. Any reason not to merge this? Do the tests fail stochastically or something?

**Comment by fywu85** [comment]
LGTM

**Pull request merged**
