### PR TITLE
Version 020

### PR DESCRIPTION
**Pull request by AboudyKreidieh**
pull everything from `berkeleyflow` and:
- renamed relevant components `flow-project` (not the website or the readthedocs though)
- changed versions to 0.2.0 (since the Flow journal release is under 0.1.0)

### CODE REVIEW

**Comment by eugenevinitsky** [comment]
Since it's impossible to read, is this an identical copy of what's on flow?

**Comment by AboudyKreidieh** [comment]
yup, fully copy-paste and is passing the tests

**Comment by eugenevinitsky** [comment]
Okay, and no upgrade of SUMO yeah? Because if we did, we need to upgrade travis.yml

**Comment by AboudyKreidieh** [comment]
no, not in this PR

**Comment by eugenevinitsky** [comment]
Thanks for doing this!

**Pull request merged**
