### PR TITLE
Better folder structure and file names

### PR DESCRIPTION
**Pull request by nathanlct**
## Pull request information

- **Status**: In development
- **Kind of changes**: File and class names of environments/scenarios, structure of example folders
- **Related PR or issue**: #564 

## Description

This PR introduces major changes to file names and folder structures, as well as fo some class names, mainly for the following folders:

- `envs`
- `multiagent_envs` (now is a subfolder under `envs`)
- `scenarios`
- `examples`
- removal of `cooperative_merge` (and `loop_merge`)

**TODO:**

- [x] better names for environments --> NL
- [x] merge `multiagent_envs` into `envs`  --> AY
- [x] better name for scenarios so that they match the environments   --> AY
- [x] better file names (e.g. `sugiyama`, `loop`,`ring` -> `ring`) --> AY, NL

This is how the new `envs` folder looks like (some classes names have also been changed):

```
envs
├── __init__.py
├── base.py
├── bay_bridge.py
├── bottleneck.py
├── merge.py
├── multiagent
│   ├── __init__.py
│   ├── base.py
│   ├── highway.py
│   ├── ring
│   │   ├── __init__.py
│   │   ├── accel.py
│   │   └── wave_attenuation.py
│   └── traffic_light_grid.py
├── ring
│   ├── __init__.py
│   ├── accel.py
│   ├── lane_change_accel.py
│   └── wave_attenuation.py
├── test.py
└── traffic_light_grid.py
```

This is how the new `scenarios` folder looks like (some classes names have also been changed):
```
scenarios/
├── __init__.py
├── base.py
├── bay_bridge.py
├── bay_bridge_toll.py
├── bottleneck.py
├── figure_eight.py
├── highway.py
├── merge.py
├── minicity.py
├── multi_ring.py
├── ring.py
└── traffic_light_grid.py
```

### CODE REVIEW

**Comment by AboudyKreidieh** [comment]
This looks great. Should we also adjust for the names of the examples and scenarios in this PR?

**Comment by nathanlct** [comment]
@AboudyKreidieh Sure, I'll do that. Also the multiagent envs.

**Comment by ashkan-software** [comment]
Thanks @nathanlct !

I think it's better if we wait a bit and discuss in the group meeting. I have discussed with @Yasharzf some good ideas about the names. Maybe we can incorporate them into these.

**Comment by ashkan-software** [comment]
I am working on this. Please wait... :)

**Comment by kjang96** [comment]
Consider linking #600, continue talking about this next week

**Comment by ashkan-software** [comment]
@AboudyKreidieh This is ready for your help now! 
@nathanlct and me already took care of environments and scenarios. You can now start working on the Examples. :)
Just to remind you, you wanted to have something like:
`python train.py "figure_eight" .....`

**Comment by ashkan-software** [comment]
Alright! All the checks are passed now. Can someone please review this? @AboudyKreidieh @eugenevinitsky?

**Comment by AboudyKreidieh** [comment]
also, this feature is for flow 0.5.0, so please hold off on merging

**Comment by ashkan-software** [comment]
@AboudyKreidieh this is a great idea. Could you just hint me on which files or which imports I need to add this? 

I think I need to add something like 
```
                """Return network for this deprecated method."""
	        warnings.simplefilter('always', PendingDeprecationWarning)
	        warnings.warn(
	            "self.k.scenario will be deprecated in a future release. Please "
	            "use self.k.network instead.",
	            PendingDeprecationWarning
	        )
```
Am I right?

**Comment by AboudyKreidieh** [comment]
@ashkan-software that's right. and in cases when they might be imported, add deprecations to the __init__.py files, as I also did in that PR

**Comment by AboudyKreidieh** [comment]
@ashkan-software can you look into the deprecation procedure? One valuable resource might be looking into how tensorflow approaches this. maybe look into tensorflow/python/util/deprecation_wrapper.py

**Comment by AboudyKreidieh** [comment]
I added a warning that looks like this:

```
__main__:1: PendingDeprecationWarning: The class flow.envs.green_wave_env.GreenWaveTestEnv is deprecated, use flow.envs.traffic_light_grid.TrafficLightGridTestEnv instead.
```

**Pull request merged**
