### PR TITLE
added Linear Adaptive Controller

### PR DESCRIPTION
**Pull request by yhb08**
## Pull request information

- **Status**: Ready to merge 
- **Kind of changes**: Added a Controller 

---

## Description

(general description)
-Added the Linear Adaptive cruise controller so that we can simulate that in the ring road scenario 
-Modified the __init__ file so that we can import the new controller implemented 
-Modified the FollowerStopper controller(it had a small mistake)

### CODE REVIEW

**Comment by eugenevinitsky** [comment]
Could you expand in the PR about what the bug was?

**Comment by yhb08** [comment]
@eugenevinitsky This is not a bug! I just added a new controller to the controllers list to simulate it in sumo!

**Comment by AboudyKreidieh** [comment]
@yhb08 can you start by resolve the pep8 incompatibilities and I'll review it afterwards.

you can find them here: https://travis-ci.com/flow-project/flow/builds/117737999

**Comment by eugenevinitsky** [comment]
> @eugenevinitsky This is not a bug! I just added a new controller to the controllers list to simulate it in sumo!

Ah, I was referring to the bug you said you fixed in the PR.

**Comment by AboudyKreidieh** [comment]
the bug fix is line 89 in the velocity_controllers.py script:
```
v = min(max(lead_vel, 0), self.v_des)
```

Walked through the paper as well and this is right.

**Comment by yhb08** [comment]
Just ignore the last thing I did, I'm fixing it

**Comment by cathywu** [comment]
@AboudyKreidieh @yhb08 Which paper is this based on? It might be good to add a reference to the paper in a comment in the implementation.

Sorry I'm late to the party!

**Comment by yhb08** [comment]
@inproceedings{Chou2018,
author={Fang-Chieh Chou and Hani Ramezani and Xiao-Yun Lu and Steven E. Shladover and Osman D. Altan},
year={2018},
title={Modeling Vehicle-Following Dynamics of Heavy Trucks Under Automatic Speed Control Based on Experimental Data},
booktitle={Transportation Research Board 97th Annual Meeting},
address={Washington DC, United States}
}


@cathywu  These are the two references: 

@article{Milanes2014,
author={Vicente Milanés and Steven E. Shladover},
year={2014},
title={Modeling cooperative and autonomous adaptive cruise control dynamic responses using experimental data},
journal={Transportation Research Part C: Emerging Technologies},
volume={48},
pages={285-300}
}

**Pull request merged**
