### PR TITLE
Missing matplotlib in conda setup

### PR DESCRIPTION
**Pull request by cathywu**
## Pull request information

- **Status**: ready to merge
- **Kind of changes**: setup
- **Related PR or issue**: N/A

## Description

Missing matplotlib in conda setup.

### CODE REVIEW

**Comment by AboudyKreidieh** [comment]
This is already in requirements.txt. Why do we need it here?

**Comment by cathywu** [comment]
My understanding is that we should eventually be able to do the full install of flow without the `requirements.txt`. However, if conda fails at any point, all the remaining dependencies are not installed, and hence it's still useful to have a requirements file sitting around.

**Comment by AboudyKreidieh** [comment]
if anything it should be the other way around. we need the `requirements.txt` file while running `pip install -e .` but not `environment.yml`. Also, anyone can always create their own environment and run the install there. Finally, people that don't want to use conda should have an option for installing flow that doesn't require it

**Comment by eugenevinitsky** [comment]
Can't hurt to have it in both places.

**Pull request merged**
