### PR TITLE
tutorial for osm

### PR DESCRIPTION
**Pull request by AboudyKreidieh**
- added a tutorial on importing networks from openstreetmap
- defaulted routes to consist of the current edge only (to make running osm files easier)
- updated the tutorials README
- added test for default scenario routes

### CODE REVIEW

**Comment by juliusfrost** [comment]
This was exactly what I was looking for with my project!

**Comment by fywu85** [comment]
Can you look into why the builds failed on Travis? Otherwise, things look pretty neat.

**Comment by AboudyKreidieh** [comment]
@fywu85 tests are passing now

**Comment by AboudyKreidieh** [comment]
@juliusfrost great to hear it! it you have any comments on this new tutorial let me know and I'd be happy to review

**Comment by xiaoToby** [comment]
I also have a problem on tutorial
My question has happened in tutorial 01.
I followed the instructions and tried to run.
There is an error, above is error description:

Traceback (most recent call last):
  File "tutorial_1.py", line 9, in <module>
    from flow.envs.loop.loop_accel import AccelEnv
  File "/Users/xiaohongzhi/flow/flow/envs/__init__.py", line 2, in <module>
    from flow.envs.base_env import Env
  File "/Users/xiaohongzhi/flow/flow/envs/base_env.py", line 37
    class Env(*classdef):
              ^
SyntaxError: invalid syntax

I cannot fix that, please help

**Pull request merged**
