### PR TITLE
Evinitsky/setupfix

### PR DESCRIPTION
**Pull request by eugenevinitsky**
Remove stable baselines from environment.yml and requirements.txt. It requires an installation of MPI which causes peoples envs to break if they don't have it.

### CODE REVIEW

**Comment by eugenevinitsky** [comment]
@AboudyKreidieh this is a two second review but super critical. The current setup instructions will break for anyone who doesn't have MPI installed.

**Comment by kjang96** [comment]
LGTM

**Comment by araffin** [comment]
Hello,
the next version of stable baselines (currently in the master branch) will support mpi less installation ;) (cf doc for details)

**Comment by eugenevinitsky** [comment]
@araffin oh great! Thanks, once that's up on pip we'll change this so it can come installed.

**Pull request merged**
